### Get All Agents

GET http://localhost:1337/agents HTTP/1.1
Accept: application/json



### Get filtered agents

GET http://localhost:1337/agents?state=CA HTTP/1.1



### GET a specific Agent
GET http://localhost:1337/agents/1 HTTP/1.1


### POST an Agent

POST http://localhost:1337/agents HTTP/1.1
Content-Type: application/json

{
    "firstName": "Steve", 
    "lastName": "Smith", 
    "phone": "555-1212", 
    "email": "Bob@aol.com",
    "stateCode": "OH"
}

### Retiring an Agent

DELETE http://localhost:1337/agents/7 HTTP/1.1


### Replacing An Agent

PUT http://localhost:1337/agents/1 HTTP/1.1
Content-Type: application/json

{
  "id": 99,
  "firstName": "John ",
  "lastName": "Cassavetes",
  "phone": "555-1213",
  "email": "john@nyfilm.com",
  "state": "OH",
  "salary": 500000
}


### MiniPut on agents email
PUT http://localhost:1337/agents/1/email HTTP/1.1
Content-Type: application/json

"john@compuserve.com"